<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><UseWPF>true</UseWPF><AssemblyName>FileViz</AssemblyName><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup>
  <ItemGroup><ProjectReference Include="../FileViz.Data/FileViz.Data.csproj" /><ProjectReference Include="../FileViz.Windows/FileViz.Windows.csproj" /><ProjectReference Include="../FileViz.Worker/FileViz.Worker.csproj" ReferenceOutputAssembly="false" /></ItemGroup>
  <Target Name="CopyWorker" AfterTargets="Build"><ItemGroup><WorkerFiles Include="$(MSBuildThisFileDirectory)../FileViz.Worker/bin/$(Configuration)/$(TargetFramework)/*.*" /></ItemGroup><Copy SourceFiles="@(WorkerFiles)" DestinationFolder="$(TargetDir)worker" SkipUnchangedFiles="true" /></Target>
</Project>